# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2c061f359f67e51b670a7050eaeb1766"
name = "insights-dashboard"
application_url = "https://insights-dashboard-pnj0.onrender.com"
embedded = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://example.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://example.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_analytics,write_metaobject_definitions,write_metaobjects,read_orders,write_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [ "https://insights-dashboard-pnj0.onrender.com/api/auth" ]

[app_proxy]
url = "https://insights-dashboard-pnj0.onrender.com/proxy"
subpath = "insights"
prefix = "apps"
